apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: monitoring
data:
  otel-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: springboot
              metrics_path: /actuator/prometheus
              static_configs:
                - targets:
                    - springboot-service.app.svc.cluster.local:80

    exporters:
      prometheusremotewrite:
        endpoint: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [prometheusremotewrite]