apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: springboot-sli-slo-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: springboot.slo
      interval: 30s
      rules:
        - record: job:springboot_success_rate:1m
          expr: |
            sum(rate(http_server_requests_seconds_count{namespace="app", status!~"5.."}[1m]))
            /
            sum(rate(http_server_requests_seconds_count{namespace="app"}[1m]))

        - record: job:springboot_slo_target
          expr: "0.999"

        - record: job:springboot_burn_rate:5m
          expr: |
            1 - (
              sum(rate(http_server_requests_seconds_count{namespace="app", status!~"5.."}[5m]))
              /
              sum(rate(http_server_requests_seconds_count{namespace="app"}[5m]))
            )

        - record: job:springboot_error_rate:5m
          expr: |
            sum(rate(http_server_requests_seconds_count{namespace="app", status=~"5.."}[5m]))
            /
            sum(rate(http_server_requests_seconds_count{namespace="app"}[5m]))
