{
 "title": "Springboot_JVM_&_Application_Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\r\njvm_memory_used_bytes{area=\"heap\"} /\r\njvm_memory_max_bytes{area=\"heap\"}\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m]) /\r\nrate(jvm_gc_pause_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}