{
 "title": "Springboot_User_Experience",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (Traffic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_requests_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_active_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}